### PR TITLE
Add code to query parameters for sharing

### PR DESCRIPTION
**Pull request by RecuencoJones**
Hi @Hopding!

Once more, thanks for this wonderful tool!
I find sharing snippets of code with others to be very useful to explain / showcase usage of micro and macrotasks.
Loupe already supports this, so I truly believe this visualizer would get a lot of benefit from using it 😄

### CODE REVIEW

**Comment by Hopding** [comment]
Hello @RecuencoJones!

I agree that this would be a very handy feature. My only concern with this as it stands is that the URLs become quite long and noisy. There's not really much way to avoid this, but it can be annoying to some users. So I'd prefer to avoid cluttering the URL unless the user explicitly asks for it. What do you think about a `Get Shareable Link` button or a `Enable Shareable Links` checkbox that turns this feature on?

**Comment by RecuencoJones** [comment]
I agree, I'll work on a way to create a share url that does not clutter user's current location 😊

**Comment by RecuencoJones** [comment]
Would it be okay like this?

image
image

The popup will close on losing focus

**Comment by Hopding** [comment]
@RecuencoJones I think that would work great! It looks very nice. Doesn't clutter anything up and is easy for the user to access.

My apologies for the late response! I meant to respond much sooner than I did. The notification got buried in my inbox, which has been flooded as of late. Trying to catch back up on everything. Work and maintaining https://github.com/Hopding/pdf-lib is keeping me busy.

Anyways, looking forward to releasing this feature 👍

**Comment by RecuencoJones** [comment]
Hi @Hopding!

Not a problem, I understand 😄 
Just pushed the changes, feel free to test them locally whenever you have some time!

**Review by Hopding — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
